/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AiMisclassification = "false_negative" | "false_positive";

export type BillStatus = "conferenceAssigned" | "conferenceDeferred" | "conferencePassed" | "conferenceScheduled" | "crossoverDeferred1" | "crossoverDeferred2" | "crossoverDeferred3" | "crossoverScheduled1" | "crossoverScheduled2" | "crossoverScheduled3" | "crossoverWaiting1" | "crossoverWaiting2" | "crossoverWaiting3" | "deferred1" | "deferred2" | "deferred3" | "governorSigns" | "introduced" | "lawWithoutSignature" | "passedCommittees" | "scheduled1" | "scheduled2" | "scheduled3" | "transmittedGovernor" | "unassigned" | "vetoList" | "waiting2" | "waiting3";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type OrgRole = "admin" | "worker";

export type Sysrole = "sysadmin" | "user";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuthKey {
  created_at: Generated<Timestamp | null>;
  google_refresh_token: string | null;
  hashed_password: string | null;
  id: Generated<string>;
  user_id: string | null;
}

export interface Bills {
  ai_misclassification_type: AiMisclassification | null;
  ai_status: BillStatus | null;
  archived: Generated<boolean>;
  bill_number: string | null;
  bill_status: Generated<BillStatus | null>;
  bill_title: string | null;
  bill_url: string;
  committee_assignment: string | null;
  created_at: Generated<Timestamp | null>;
  current_status_string: string;
  dead: Generated<boolean>;
  description: string;
  food_related: Generated<boolean | null>;
  id: Generated<string>;
  introducer: string | null;
  nickname: string | null;
  updated_at: Generated<Timestamp | null>;
  year: number | null;
}

export interface BillTags {
  bill_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  tag_id: string;
}

export interface BillVersions {
  ai_summary: string | null;
  bill_id: string;
  created_at: Generated<Timestamp | null>;
  html_link: string | null;
  id: Generated<string>;
  label: string;
  original_text: string | null;
  pdf_link: string | null;
  updated_at: Generated<Timestamp | null>;
}

export interface CommitteeReports {
  ai_summary: string | null;
  bill_id: string;
  created_at: Generated<Timestamp | null>;
  html_link: string | null;
  id: Generated<string>;
  label: string;
  original_text: string | null;
  pdf_link: string | null;
  report_code: string | null;
  updated_at: Generated<Timestamp | null>;
}

export interface InviteTokens {
  accepted_at: Timestamp | null;
  created_at: Generated<Timestamp | null>;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  invited_by: string;
  status: Generated<string>;
  tenant_id: string;
  token: string;
}

export interface Legislators {
  area: string | null;
  chamber: string | null;
  created_at: Generated<Timestamp>;
  district: number | null;
  email: string | null;
  first_name: string | null;
  id: Generated<string>;
  in_office: Generated<boolean>;
  last_name: string | null;
  member_id: string;
  party: string | null;
  phone: string | null;
  room: string | null;
  term_ended: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface Members {
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  org_role: Generated<OrgRole>;
  tenant_id: string;
  user_id: string;
}

export interface OrgBills {
  bill_id: string;
  bill_status: Generated<BillStatus>;
  tenant_id: string;
  updated_at: Generated<Timestamp | null>;
}

export interface OrgFollows {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  tenant_id: string;
  user_id: string;
}

export interface PendingProposals {
  approval_status: Generated<string | null>;
  approved_at: Timestamp | null;
  approved_by_user_id: string | null;
  bill_id: string;
  current_status: string;
  id: Generated<string>;
  note: string | null;
  proposed_at: Generated<Timestamp>;
  proposed_by_user_id: string;
  proposed_status: string;
  tenant_id: string | null;
}

export interface SchemaMigrations {
  dirty: boolean;
  version: Int8;
}

export interface ScrapingStats {
  bills_scraped: Generated<number | null>;
  created_at: Generated<Timestamp | null>;
  error_message: string | null;
  id: Generated<string>;
  last_scrape_time: Timestamp;
  success: Generated<boolean | null>;
}

export interface Sessions {
  created_at: Generated<Timestamp | null>;
  expires_at: Timestamp;
  id: Generated<string>;
  session_token: string;
  user_id: string | null;
}

export interface StatusUpdates {
  bill_id: string;
  chamber: string;
  date: string;
  id: Generated<string>;
  statustext: string;
}

export interface SupervisorUsers {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  supervisor_id: string;
  user_id: string;
}

export interface Tags {
  color: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Tenants {
  branding_config: Json | null;
  created_at: Generated<Timestamp | null>;
  description: Generated<string>;
  id: Generated<string>;
  name: string;
  public_board: Generated<boolean>;
  slug: string;
}

export interface Testimonies {
  author_name: Generated<string>;
  bill_id: string;
  content_json: Generated<Json>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  organization: Generated<string>;
  position: Generated<string>;
  submitted_at: Generated<Timestamp | null>;
  tenant_id: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface User {
  account_status: string;
  auth_provider: Generated<string | null>;
  created_at: Generated<Timestamp | null>;
  email: string;
  email_verified: Generated<boolean | null>;
  google_id: string | null;
  id: Generated<string>;
  profile_picture_url: string | null;
  requested_admin: Generated<boolean>;
  requested_supervisor: Generated<boolean | null>;
  role: Generated<string>;
  system_role: Generated<Sysrole>;
  username: string;
  verification_token: string | null;
}

export interface UserBillPreferences {
  bill_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  nickname: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface UserBills {
  adopted_at: Generated<Timestamp | null>;
  bill_id: string | null;
  id: Generated<string>;
  tenant_id: string | null;
  user_id: string | null;
}

export interface UserPreferences {
  ai_opt_in: Generated<boolean>;
  created_at: Generated<Timestamp>;
  kanban_detailed_view: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface DB {
  auth_key: AuthKey;
  bill_tags: BillTags;
  bill_versions: BillVersions;
  bills: Bills;
  committee_reports: CommitteeReports;
  invite_tokens: InviteTokens;
  legislators: Legislators;
  members: Members;
  org_bills: OrgBills;
  org_follows: OrgFollows;
  pending_proposals: PendingProposals;
  schema_migrations: SchemaMigrations;
  scraping_stats: ScrapingStats;
  sessions: Sessions;
  status_updates: StatusUpdates;
  supervisor_users: SupervisorUsers;
  tags: Tags;
  tenants: Tenants;
  testimonies: Testimonies;
  user: User;
  user_bill_preferences: UserBillPreferences;
  user_bills: UserBills;
  user_preferences: UserPreferences;
}
