/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Bills {
  bill_number: string | null;
  bill_title: string | null;
  bill_url: string;
  committee_assignment: string | null;
  created_at: Generated<Timestamp>;
  current_status: string;
  description: string;
  id: Generated<string>;
  introducer: string | null;
  updated_at: Generated<Timestamp>;
}

export interface SchemaMigrations {
  dirty: boolean;
  version: Int8;
}

export interface ScrapingStats {
  bills_scraped: Generated<number>;
  created_at: Generated<Timestamp>;
  error_message: string | null;
  id: Generated<string>;
  last_scrape_time: Timestamp;
  success: Generated<boolean>;
}

export interface DB {
  bills: Bills;
  schema_migrations: SchemaMigrations;
  scraping_stats: ScrapingStats;
}
